[build]
  command = "npm install"
  functions = "functions"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm start"
  port = 5000

[functions]
  node_bundler = "nft"