[run]
cmd = "npm start"

[deployment]
run = ["npm", "start"]
deploymentTarget = "autoscale"
ignorePorts = false

[env]
NODE_ENV = "production"
PORT = "5000"
HOST = "0.0.0.0"

[nix]
channel = "stable-24_05"

[languages]

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx,*.json}"

[languages.javascript.languageServer]
start = "typescript-language-server --stdio"