[run]
cmd = "npm start"

[deployment]
build = ["npm", "install", "--production"]
run = ["npm", "start"]
deploymentTarget = "autoscale"
ignorePorts = false
publicDir = "."

[env]
NODE_ENV = "production"

[nix]
channel = "stable-24_05"

[unitTest]
language = "nodejs"

[debugger]
support = true

[languages]

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx,*.json}"

[languages.javascript.languageServer]
start = "typescript-language-server --stdio"

[gitHubImport]
requiredFiles = [".replit", "replit.toml"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"
HOST = "0.0.0.0"